### ISSUE TITLE
Problem when list all plans

### ISSUE THREAD

**Issue by netodevel** [paniko0/jassinaturas#7]
`"Method has too many Body parameters: public abstract sdk.jassinaturas.clients.attributes.Plan sdk.jassinaturas.communicators.PlanCommunicator.update(java.lang.String,sdk.jassinaturas.clients.attributes.Plan)""`

**Comment by paniko0** [comment]
I didn't get it. Is it happening when you list plans or when you update a plan?

**Comment by netodevel** [comment]
@paniko0 
Sorry for opening the issue actually the error happened because I had another depedency that also used the most updated feign library, and ended up having conflict in maven's pom.xml. Thanks for the feedback.
